- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - build-essential
      - openssh-server
      - nfs-common
      - ncdu
      - git